---
permalink: phases/plan-prepare-phase.html 
sidebar: sidebar 
keywords: plan and prepare phase, foreign lun import, fli, migration planning, test migration, cutover, intercluster lif, iscsi fli, gap analysis, san migration, fc fli, zoning, test migration 
summary: Eseguire una o più migrazioni di prova per confermare che gli array, la rete e il fabric, la configurazione ONTAP e le procedure di correzione degli host siano corrette, e per raccogliere campioni di throughput che possano essere estrapolati per la pianificazione in produzione. 
---
= Pianificazione della migrazione di prova e del cutover per ONTAP Foreign LUN Import (FLI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eseguire una o più migrazioni di prova per confermare che gli array, la rete e il fabric, la configurazione ONTAP e le procedure di correzione degli host siano corrette, e per raccogliere campioni di throughput che possano essere estrapolati per la pianificazione in produzione.

Una buona migrazione di prova convalida:

* Prontezza del backend: la raggiungibilità dell'IC LIF, la stabilità delle sessioni iSCSI e il rilevamento dei LUN esterni sono coerenti su tutti i percorsi.
* Correttezza del flusso di lavoro: la creazione/avvio/visualizzazione/completamento (e la verifica facoltativa) della relazione di importazione si comporta come previsto nella modalità selezionata (online/offline).
* Preparazione dell'host: le procedure di scansione/correzione dell'host funzionano in modo affidabile per il caso d'uso di destinazione (ad esempio, ESXi VMFS/RDM, Windows standalone/WFC).
* Stime operative: il throughput osservato nelle prove fornisce la base più realistica per stimare la durata della migrazione in produzione ed è generalmente migliore di qualsiasi benchmark.




[[test-migration-example-using-hitachi-ams2100]]
== Esempio di migrazione di test con Hitachi AMS2100

Di seguito viene riportato un esempio di migrazione di test utilizzando un Hitachi AMS2100 come array esterno. A seconda degli array coinvolti, dei sistemi operativi host e di altre variabili, i passaggi potrebbero essere diversi.

È possibile utilizzare il seguente esempio come guida generale ai passaggi necessari per eseguire migrazioni di test. NetApp consiglia di eseguire le migrazioni dei test il prima possibile per trovare e avere il più tempo possibile per risolvere eventuali problemi riscontrati dai test. Prima di procedere con la migrazione in produzione, è necessario eseguire una migrazione di test su tutte le combinazioni di array di origine e di destinazione.

.Fasi
. Creare un LUN di test da 2 GB sull'array di origine.
+
.. Accedi a Hitachi Storage Navigator Modular come  `system`.
.. Selezionare *array AMS 2100*.
.. Fare clic su *Show and Configure Array* (Mostra e configura array).
.. Accedi utilizzando  `root`.
.. Espandere *gruppi* e selezionare *unità logiche*.
.. Selezionare *Create LU* (Crea LUN) per creare il LUN di prova.
.. Creare un LUN di prova di 2 GB.
.. Fare clic su *OK*.
.. Ignorare l'assegnazione del LUN qui e procedere facendo clic su *Chiudi*.
.. Verificare che la LUN di test sia stata creata.


. Assegnare la LUN di test al gruppo host creato per gli initiator ONTAP.
+
.. Espandere *gruppi* e selezionare *unità logiche*.
.. Selezionare *Gruppi host* per mappare la LUN di test al gruppo host *cDOT_FLI*.
.. Seleziona il gruppo host *cDOT_FLI* creato nel passaggio precedente e fai clic su *Modifica gruppo host*.
.. Selezionare le porte per il gruppo host. In questo esempio scegliamo *0a*, *0e*, *1a*, *1e*. Selezionare l'opzione *Imposta forzatamente su tutte le porte selezionate*.
.. Nell'HDS Storage Navigator, modificare il gruppo host.
.. Fai clic su *Unità logiche* e aggiungi la LUN di test.
.. Fare clic su *OK* per mappare il LUN.
.. Selezionare *Sì, ho ricevuto l'avviso riportato sopra e si desidera modificare il gruppo di host* e fare clic su *Conferma*.
.. Verificare la creazione del gruppo host e fare clic su *Chiudi*.


. Verificare il LUN di prova e la mappatura dallo storage di origine allo storage di destinazione ed eseguire l'importazione di LUN esterne (FLI).
+
.. Accedere allo storage ONTAP tramite SSH utilizzando l’ `admin`utente.
.. Imposta la modalità su *Avanzata*.
+
DataMig-cmode::> set -privilege advanced

.. Digita 'y' quando ti viene chiesto se desideri continuare con i comandi avanzati.
.. Rileva l'array sorgente su ONTAP. Attendi qualche minuto e riprova a rilevare l'array sorgente.
+
storage array show

+
Quando lo storage array viene rilevato per la prima volta, ONTAP potrebbe non visualizzare l'array rilevando automaticamente. Seguire le istruzioni riportate di seguito per ripristinare la porta dello switch a cui sono collegate le porte ONTAP Initiator.

+
Ad esempio, le porte initiator del cluster DataMig-cmode `0a` e `0b` di ONTAP sono collegate alle porte Cisco `4/9` e `4/11`. Per reimpostare la porta `4/9` sullo switch Cisco:

+
[listing]
----
conf t
interface fc4/
shutdown
no shutdown
exit
exit
----
+
Il ripristino di una porta è in genere sufficiente. Controllare l'elenco di array e i percorsi LUN dopo aver reimpostato una porta.

.. Verificare che l'array sorgente venga rilevato attraverso tutte le porte initiator:
+
storage array config show -array-name HITACHI_DF600F_1

+
[listing]
----
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
.. Elenca la LUN di test mappata dallo storage Hitachi e verifica le proprietà del disco e i percorsi:
+
storage disk show -array-name HITACHI_DF600F_1 -instance

+
[listing]
----

                  Disk: HIT-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: HITACHI_DF600F_1
                Vendor: HITACHI
                 Model: DF600F
         Serial Number: 83017542001A
                   UID: 48495441:43484920:38333031:37353432:30303236:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                            Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port     TPGN    Speed  I/O KB/s  IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  --------------  ------  ----   --- -----
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0

Errors:
-

DataMig-cmode::*>
----


. Contrassegnare la LUN di origine come esterna utilizzando il numero di serie:
+
disco di archiviazione set-foreign-lun { -serial-number 83017542001A } -is-foreign true

+
.. Verificare che la LUN di origine sia contrassegnata come esterna:
+
storage disk show -array-name HITACHI_DF600F_1

.. Elenca tutti gli array esterni e i relativi numeri di serie:
+
storage disk show -container-type foreign -fields serial-number

+

NOTE: Il comando LUN create rileva le dimensioni e l'allineamento in base all'offset della partizione e crea il LUN di conseguenza con l'argomento del disco esterno.



. Creare un volume di destinazione:
+
vol create -vserver datamig flivol aggr1 -size 10g

. Creare una LUN di test utilizzando una LUN esterna:
+
lun create -vserver datamig -path /vol/flivol/testlun1 -ostype linux -foreign-disk 83017542001A

+
.. Elenca il LUN di test e verifica le dimensioni del LUN confrontandole con quelle del LUN di origine:
+
lun show

+

NOTE: Per la migrazione offline FLI, il LUN deve essere online per mapparlo a un igroup e quindi offline prima di creare la relazione di importazione del LUN.



. Creare un gruppo di test igroup del protocollo FCP senza aggiungere alcun initiator:
+
lun igroup create -vserver datamig -igroup testig1 -protocol fcp -ostype linux

. Mappa la LUN di test all'igroup di test:
+
lun map -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Porta offline il LUN di test:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

. Creare una relazione di importazione con LUN di test e LUN esterna:
+
lun import create -vserver datamig -path /vol/flivol/testlun1 -foreign-disk 83017542001A

. Avviare la migrazione (importazione):
+
lun import start -vserver datamig -path /vol/flivol/testlun1

+
.. Monitora l'avanzamento dell'importazione:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

.. Verifica che l'import job sia stato completato correttamente:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           import    started
                                                           completed     100
----


. Avviare il processo di verifica per confrontare le LUN di origine e di destinazione. Monitorare l'avanzamento della verifica:
+
lun import verify start -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -path /vol/flivol/testlun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           in_progress     44
----
+
.. Verifica che il processo di verifica sia stato completato senza errori:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           completed      100
----


. Elimina la relazione di importazione per rimuovere il processo di migrazione:
+
lun import delete -vserver datamig -path /vol/flivol/testlun1

+
lun import show -vserver datamig -path /vol/flivol/testlun1

. Rimuovi la LUN di test dall'igroup di test:
+
lun unmap -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Online il test LUN:
+
lun online -vserver datamig -path /vol/flivol/testlun1

. Imposta l'attributo LUN esterno su falso:
+
storage disk modify -serial-number 83017542001A -is-foreign false

+

NOTE: Non rimuovere il gruppo di host creato sullo storage di origine con le porte ONTAP Initiator. Lo stesso gruppo di host viene riutilizzato durante le migrazioni dall'array di origine.

. Rimuovere il LUN di test dallo storage di origine.
+
.. Accedere a Hitachi Storage Navigator Modular come sistema.
.. Seleziona *AMS 2100 array* e fai clic su *Mostra e configura array*.
.. Accedi utilizzando  `root`.
.. Selezionare *gruppi*, quindi *gruppi di host*.
.. Seleziona *cDOT_FLI Igroup* e fai clic su *Modifica gruppo host*.
.. Nella finestra Modifica gruppo host, selezionare tutte le porte di destinazione scelte per mappare la LUN di test e selezionare *Imposta forzatamente su tutte le porte selezionate*.
.. Selezionare la scheda *Logical Units* (unità logiche).
.. Selezionare il LUN di prova dalla finestra *Assigned Logical Units* (unità logiche assegnate).
.. Selezionare *Remove* (Rimuovi) per rimuovere la mappatura del LUN.
.. Fare clic su *OK*.


. Non rimuovere il gruppo host e continuare a eliminare il LUN di prova.
+
.. Selezionare *Unità logiche*.
.. Selezionare la LUN di test creata nel passaggio precedente.
.. Fare clic su *Delete LUN* (Elimina LUN).
.. Fare clic su *Confirm* (Conferma) per eliminare il LUN di prova.


. Eliminare il LUN di prova sullo storage di destinazione.
+
.. Accedere al sistema storage ONTAP tramite SSH utilizzando  `admin` user.
.. Offline la LUN di test sul sistema storage NetApp:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

+

NOTE: Assicurarsi di non selezionare un altro LUN host.

.. Eliminare la LUN di test sul sistema storage NetApp:
+
lun destroy -vserver datamig -path /vol/flivol/testlun1

.. Offline il volume di test sul sistema storage NetApp:
+
vol offline -vserver datamig -volume flivol

.. Elimina il volume di test sul sistema storage NetApp:
+
vol destroy -vserver datamig -volume flivol




