---
permalink: san-migration/concept_7_mode_to_ontap_supported_configurations.html 
sidebar: sidebar 
keywords: 7-mode, ontap, fli, supported, configurations 
summary: 'È importante verificare che il sistema operativo host, l"HBA, lo switch e l"array ONTAP a cui si sta effettuando la transizione siano supportati.' 
---
= Configurazioni supportate da 7-Mode a ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È importante verificare che il sistema operativo host, l'HBA, lo switch e l'array ONTAP a cui si sta effettuando la transizione siano supportati.

Se si utilizza il flusso di lavoro di transizione da FLI 7-Mode a ONTAP , non è necessario verificare la sorgente (controller 7-Mode) IMT. Non verrà elencato ma è supportato espressamente per questo flusso di lavoro di transizione. È comunque necessario verificare che tutti gli host siano in una configurazione supportata.

Non esistono requisiti specifici per la piattaforma FLI. Non sono disponibili versioni minime di 7-Mode Data ONTAP, anche se la versione dovrebbe supportare il protocollo Fibre Channel (FCP).

La dimensione massima del LUN che FLI può importare è di 6 TB. Si tratta di un limite basato sulle dimensioni massime correnti dei dischi attualmente supportati da ONTAP. Se si tenta di montare un LUN esterno più grande, il LUN viene contrassegnato come rotto e non è possibile scrivervi un'etichetta.
