---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: A partire da ONTAP 9.1, AFF supporta FLI. È possibile utilizzare FLI per importare LUN da altri array direttamente nei cluster ONTAP . 
---
= Utilizzo di importazione LUN esterna per importare LUN in AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.1, AFF supporta FLI. È possibile utilizzare FLI per importare LUN da altri array direttamente nei cluster ONTAP .

A partire da ONTAP 8.3.2, AFF può supportare FLI con una richiesta di variazione del processo (PVR) approvata. Contatta il team del tuo account NetApp per inviare il PVR per l'approvazione. Dopo l'approvazione, il richiedente, solitamente un NetApp System Engineer, riceverà una lettera di approvazione con le istruzioni per abilitare la funzionalità FLI.

Per le versioni del software ONTAP precedenti alla 8.3.2, sarà necessario organizzare le importazioni FLI in una coppia HA non AFF sullo stesso cluster con AFF. Una volta completata la migrazione, è possibile utilizzare operazioni non distruttive (NDO), come vol o LUN move, per spostare i LUN migrati in AFF. Se il tuo cluster AFF non ha nodi non AFF , parla con il tuo account team della possibilità di prendere in prestito un'attrezzatura di oscillazione per facilitare questa operazione.
