---
permalink: san-migration/concept_lun_requirements_and_limitations.html 
sidebar: sidebar 
keywords: lun, requirements, limitations 
summary: I LUN devono soddisfare i seguenti requisiti prima di iniziare una migrazione FLI. 
---
= Requisiti e limitazioni del LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I LUN devono soddisfare i seguenti requisiti prima di iniziare una migrazione FLI.

* FLI richiede almeno una porta FC su ciascun controller e la migrazione DEI LUN direttamente in modalità Initiator.
* La LUN esterna deve essere contrassegnata come esterna nell'array di destinazione per impedire assegnazioni da parte di ONTAP.
* Prima di iniziare l'importazione, il LUN estero deve trovarsi in una relazione di importazione.
* La LUN deve avere le stesse dimensioni della LUN esterna. Questo requisito viene soddisfatto durante le fasi di creazione della LUN.
* La dimensione del blocco LUN esterno deve essere 512b. Le LUN NetApp supportano solo blocchi di dimensioni pari a 512 b.
* Il LUN non deve espandersi o contrarsi.
* Il LUN deve essere mappato ad almeno un igroup.
* Prima di creare una relazione, è necessario disattivare la LUN NetApp . Tuttavia, dopo aver creato la relazione LUN, è possibile ripristinarla online in caso di FLI online.




== Limitazioni

* Tutte le migrazioni sono a livello di LUN.
* FLI supporta solo connessioni Fibre Channel (FC).
* FLI non supporta direttamente le connessioni iSCSI. Per eseguire la migrazione dei LUN iSCSI mediante FLI, il tipo di LUN deve essere modificato in FC. Al termine della migrazione, il tipo di LUN viene nuovamente modificato in iSCSI.

