---
permalink: san-migration/reference_site_survey_and_planning_worksheet_lun_details_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, lun details tab 
summary: 'Come parte del foglio di lavoro Site Survey and Planning (sondaggio e pianificazione del sito), è necessario disporre di una scheda contenente informazioni sui dettagli del LUN.' 
---
= Scheda Dettagli LUN del foglio di lavoro Site Survey and Planning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Come parte del foglio di lavoro Site Survey and Planning (sondaggio e pianificazione del sito), è necessario disporre di una scheda contenente informazioni sui dettagli del LUN.

Di seguito viene riportato un esempio di configurazione della scheda LUN Details (Dettagli LUN).

|===
5+| Dettagli LUN 


 a| 
Origine



 a| 
Host Name (Nome host)
 a| 
Gruppo di storage
 a| 
Sistema operativo
 a| 
In cluster
 a| 
Controller dello storage



 a| 
dm-rx200s6-21
 a| 
dm-rx200s6-21
 a| 
Microsoft Windows Server 2012 R2 Datacenter
 a| 
No
 a| 
AMS2100



 a| 
dm-rx200s6-22
 a| 
dm-rx200s6-22
 a| 
Red Hat Enterprise Linux Server versione 5.10
 a| 
No
 a| 
AMS2100



 a| 
dm-rx200s6-20
 a| 
dm-rx200s6-20
 a| 
ESXi 5.5.0 build-1331820
 a| 
No
 a| 
AMS2100



 a| 
dm-rx200s6-20
 a| 
dm-rx200s6-20
 a| 
ESXi 5.5.0 build-1331820
 a| 
No
 a| 
AMS2100

|===
|===
5+| Dettagli LUN 


 a| 
Origine



 a| 
Punto di montaggio
 a| 
Numero di disco fisico
 a| 
Porta
 a| 
Autobus
 a| 
Destinazione



 a| 
C:
 a| 
PHYSICALDRIVE0
 a| 
2
 a| 
0
 a| 
0



 a| 
/
 a| 
sda
 a| 
0
 a| 
0
 a| 
0



 a| 
BootLUN_Datastore
 a| 
naa.60060e801046b96004f2bf4600000014
 a| 
0
 a| 
0
 a| 
0



 a| 
VM_Datastore
 a| 
naa.60060e801046b96004f2bf4600000015
 a| 
0
 a| 
0
 a| 
0

|===
|===
5+| Dettagli LUN 


 a| 
Origine



 a| 
LUN
 a| 
N. DI SERIE PG80
 a| 
SN/UID PG83
 a| 
Dimensioni LUN (GB)
 a| 
Offset iniziale



 a| 
0
 a| 
 a| 
60060e801046b96004f2bf460000001e
 a| 
40
 a| 
0



 a| 
0
 a| 
 a| 
60060e801046b96004f2bf4600000010
 a| 
20
 a| 



 a| 
0
 a| 
 a| 
60060e801046b96004f2bf4600000014
 a| 
20
 a| 



 a| 
1
 a| 
 a| 
60060e801046b96004f2bf4600000015
 a| 
40
 a| 

|===
|===
5+| Dettagli LUN 


 a| 
Origine



 a| 
Tipo di LUN
 a| 
Allineato
 a| 
Prefisso personalizzato (blocchi)
 a| 
Prefisso personalizzato (byte)
 a| 



 a| 
windows
 a| 
Allineato
 a| 
0
 a| 
0
 a| 



 a| 
linux
 a| 
Allineato
 a| 
0
 a| 
0
 a| 



 a| 
vmware
 a| 
Allineato
 a| 
0
 a| 
0
 a| 



 a| 
vmware
 a| 
Allineato
 a| 
0
 a| 
0
 a| 

|===