---
permalink: san-migration/reference_site_survey_and_planning_worksheet_storage_groups_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, storage groups tab 
summary: 'Nell"ambito del foglio di lavoro Site Survey and Planning, è necessario disporre di una scheda contenente informazioni sui gruppi di storage.' 
---
= Scheda Storage Groups del foglio di lavoro Site Survey and Planning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nell'ambito del foglio di lavoro Site Survey and Planning, è necessario disporre di una scheda contenente informazioni sui gruppi di storage.

Di seguito viene riportato un esempio di configurazione della scheda Storage Groups (gruppi di storage).

|===
4+| Gruppi di storage 


 a| 
Origine
 a| 
Destinazione



 a| 
Host Name (Nome host)
 a| 
Gruppo di storage
 a| 
PN. WWN
 a| 
Comandi di iGroup



 a| 
dm-rx200s6-21
 a| 
dm-rx200s6-21
 a| 
21:00:00:24:ff:30:14:c521:00:00:24:ff:30:14:c4
 a| 
`igroup create -ostype` windows `-protocol` fcp `-vserver` datamig `-igroup` dm-rx200s6-21 `-initiator` 21:00:00:24:ff:30:c4,21:00:00:14 24:ff:30:14:c5



 a| 
dm-rx200s6-22
 a| 
dm-rx200s6-22
 a| 
21:00:00:24:ff:30:04:8521:00:00:24:ff:30:04:84
 a| 
`igroup create -ostype` linux `-protocol` fcp `-vserver` datamig `-igroup` dm-rx200s6-22 `-initiator` 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84



 a| 
dm-rx200s6-20
 a| 
dm-rx200s6-20
 a| 
21:00:00:24:ff:30:03:ea21:00:00:24:ff:30:03:eb
 a| 
`igroup create -ostype` vmware `-protocol` fcp `-vserver` datamig -`igroup` dm-rx200s6-20 `-initiator` 21:00:00:24:ff:30:03:ea, 21:00:00:24:ff:30:03:eb

|===