---
permalink: san-migration/remove-lun-import-relationship-online.html 
sidebar: sidebar 
keywords: clean up, fli, online migration 
summary: Una volta completata la migrazione online di FLI, la relazione di importazione del LUN viene rimossa. 
---
= Rimuovere la relazione di importazione LUN dopo una migrazione online FLI ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta completata la migrazione online dell'importazione FLI (Foreign LUN Import), la relazione di importazione LUN può essere rimossa in modo sicuro. L'host ora accede al nuovo array NetApp per tutti gli I/O sulla nuova LUN ONTAP e la LUN di origine non è più in uso.

A partire da ONTAP 9.17.1, la migrazione dei dati di LUN estranee utilizzando la migrazione offline FLI è supportata da link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemi ASA r2"^]. I sistemi ASA r2 differiscono dagli altri sistemi ONTAP (ASA, AFF e FAS) nell'implementazione del loro livello di archiviazione. ASA creati automaticamente quando viene creata un'unità di archiviazione (LUN o namespace). Ogni volume contiene una sola unità di archiviazione. Pertanto, per i sistemi ASA r2, non è necessario includere il nome del volume nel file  `-path` opzione durante la creazione del LUN; dovresti invece includere il percorso dell'unità di archiviazione.

.Fasi
. Eliminare la relazione di importazione del LUN.
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. Verificare che la relazione di importazione sia stata eliminata.
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
. Facoltativamente, visualizza il registro eventi per verificare i risultati della migrazione.
+
[source, cli]
----
event log show –event fli*
----
+
Questo esempio mostra un output di esempio del comando per visualizzare il registro eventi per i risultati della migrazione FLI.

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.Cosa succederà ora?
link:concept_fli_online_post_migration_tasks.html["Eseguire attività post-migrazione"] .
