---
permalink: san-migration/task_fli_online_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli online, verify, migration, results 
summary: Un lavoro di verifica è facoltativo, ma consigliato. Si tratta di un confronto blocco per blocco delle LUN di origine e di destinazione. Verificare che i processi richiedano quasi lo stesso tempo o un tempo leggermente superiore rispetto al tempo di migrazione. 
---
= Verifica i risultati della migrazione online ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo la migrazione della LUN dall'array esterno all'array ONTAP , Foreign LUN Import (FLI) può eseguire un confronto blocco per blocco delle LUN di origine e di destinazione per verificare che la migrazione sia completa e accurata. La verifica della migrazione richiede all'incirca lo stesso tempo (o leggermente superiore) della migrazione stessa.

La verifica della migrazione non è obbligatoria, ma è altamente consigliata.

.Informazioni su questo compito
* A partire da ONTAP 9.17.1, la migrazione dei dati di LUN estranee utilizzando la migrazione offline FLI è supportata da link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemi ASA r2"^]. I sistemi ASA r2 differiscono dagli altri sistemi ONTAP (ASA, AFF e FAS) nell'implementazione del loro livello di archiviazione. ASA creati automaticamente quando viene creata un'unità di archiviazione (LUN o namespace). Ogni volume contiene una sola unità di archiviazione. Pertanto, per i sistemi ASA r2, non è necessario includere il nome del volume nel file  `-path` opzione durante la creazione del LUN; dovresti invece includere il percorso dell'unità di archiviazione.
* La verifica della migrazione è discontinua. Le LUN in fase di verifica devono essere offline per tutta la durata della verifica.


.Fasi
. Offline i LUN da verificare.
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Questo esempio mostra il comando per mettere offline la LUN denominata *72Clun1* nel volume *flivol* e nella SVM *fli_72C*.

+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1
Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y
----
+
La finestra di interruzione inizia qui.

. Avviare la verifica della migrazione LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. Monitorare lo stato della verifica.
+
[source, cli]
----
lun import show -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Questo esempio mostra il comando per monitorare lo stato di verifica per la LUN denominata *72Clun1* nel volume *flivol* e nella SVM *fli_72C*.

+
[listing]
----
ontaptme-fc-cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 verify    started
                                                                        9
----
. Interrompere la verifica LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
La verifica dell'importazione della LUN deve essere interrotta esplicitamente prima di riattivare la LUN. In caso contrario, la LUN non sarà online. Questo passaggio deve essere eseguito manualmente anche se lo stato indica che la verifica è completa.

. LUN online.
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
La finestra di interruzione termina qui.



.Cosa succederà ora?
link:remove-lun-import-relationship-online.html["Rimuovere la relazione di importazione LUN"] .
