---
permalink: san-migration/task_verifying_source_luns_on_destination_storage_for_offline_foreign_lun_import.html 
sidebar: sidebar 
keywords: verify, source luns, destination storage, offline fli 
summary: 'Nell"ambito del processo di importazione dei LUN esteri offline, è necessario verificare i LUN di origine nello storage di destinazione.' 
---
= Verifica dei LUN di origine sullo storage di destinazione per gli FLI offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nell'ambito del processo di importazione dei LUN esteri offline, è necessario verificare i LUN di origine nello storage di destinazione.

.Fasi
. Verificare i LUN di origine e la mappatura dallo storage di origine allo storage di destinazione.
. Accedere allo storage ONTAP tramite SSH utilizzando admin user.
. Impostare la modalità su Advanced (Avanzate): `set -privilege advanced`
. Invio `y` quando viene richiesto se si desidera continuare.
. Scopri l'array di origine su ONTAP. Attendere alcuni minuti e riprovare a rilevare l'array di origine. `storage array show`
+
[listing]
----
DataMig-cmode::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
Quando lo storage array viene rilevato per la prima volta, ONTAP potrebbe non visualizzare l'array rilevando automaticamente. Seguire le istruzioni riportate di seguito per ripristinare la porta dello switch a cui sono collegate le porte ONTAP Initiator.

====
. Verificare che l'array di origine venga rilevato attraverso tutte le porte dell'iniziatore.
+
[listing]
----
DataMig-cmode::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
. Elencare i LUN di origine mappati dallo storage Hitachi. Verificare le proprietà e i percorsi del disco.
+
Il numero di percorsi previsti dipende dal cablaggio (almeno due percorsi per ciascun controller di origine). È inoltre necessario controllare il registro eventi dopo aver mascherato le LUN dell'array.

+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

DataMig-cmode::*>
----

