---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: Un lavoro di verifica è facoltativo, ma consigliato. Si tratta di un confronto blocco per blocco delle LUN di origine e di destinazione. Verificare che i processi richiedano quasi lo stesso tempo o un tempo leggermente superiore rispetto al tempo di migrazione. 
---
= Verifica i risultati della migrazione offline ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo la migrazione di una LUN dall'array esterno al sistema di storage ONTAP , FLI può eseguire un confronto blocco per blocco delle LUN di origine e di destinazione per verificare che la migrazione sia completa e accurata. La verifica della migrazione richiede all'incirca lo stesso tempo (o leggermente superiore) della migrazione stessa.

La verifica della migrazione non è obbligatoria, ma è altamente consigliata.

.Informazioni su questo compito
A partire da ONTAP 9.17.1, la migrazione dei dati di LUN estranee utilizzando la migrazione offline FLI è supportata da link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemi ASA r2"^]. I sistemi ASA r2 differiscono dagli altri sistemi ONTAP (ASA, AFF e FAS) nell'implementazione del loro livello di archiviazione. ASA creati automaticamente quando viene creata un'unità di archiviazione (LUN o namespace). Ogni volume contiene una sola unità di archiviazione. Pertanto, per i sistemi ASA r2, non è necessario includere il nome del volume nel file  `-path` opzione durante la creazione del LUN; dovresti invece includere il percorso dell'unità di archiviazione.

.Fasi
. Avviare la verifica della migrazione LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Questo esempio mostra il comando per avviare la verifica della migrazione LUN per le LUN denominate *bootlun*, *fdrive* e *gdrive* nel volume *winvol* e nella SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. Monitorare lo stato della verifica.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
Questo esempio mostra il comando per monitorare lo stato di verifica per l'SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
È possibile eseguire lo stesso comando per monitorare l'avanzamento della verifica. *operational-state* visualizza lo stato *completed* quando il processo di verifica è stato completato con successo.

. Interrompere la verifica LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Questo esempio mostra il comando per interrompere la verifica LUN per l'SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
La verifica dell'importazione LUN deve essere interrotta esplicitamente prima di riportare online la LUN. In caso contrario,  `lun online` Il comando fallisce. Questo passaggio deve essere eseguito manualmente anche se lo stato indica che la verifica è completata.



.Cosa succederà ora?
link:remove-lun-import-relationship-offline.html["Rimuovere la relazione di importazione LUN"] .
