---
permalink: san-migration/task_fli_transition_preparing_source_and_destination_arrays.html 
sidebar: sidebar 
keywords: prepare, source, destination, arrays, migration 
summary: 'Per prepararsi alla migrazione da FLI 7-mode a ONTAP, verificare i percorsi del LUN di origine e dell"host e altri dettagli.' 
---
= Preparazione degli array di origine e di destinazione per la migrazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per prepararsi alla migrazione da FLI 7-mode a ONTAP, verificare i percorsi del LUN di origine e dell'host e altri dettagli.

.Fasi
. In ONTAP, passare a. `advanced` livello di privilegio.
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster::*>
----
. Verificare che l'array di origine sia visibile sul controller di destinazione.
+
[listing]
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
NET-1                    NETAPP_LUN_1   NETAPP              LUN

cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Visualizza i dettagli sugli errori di storage elencati. Alcuni errori potrebbero richiedere un'azione prima di procedere. Tuttavia, gli errori mostrati nell'esempio seguente, "`questo dispositivo è un LUN ONTAP(R)`". può essere ignorato in modo sicuro.
+
[NOTE]
====
Il messaggio di errore "questo dispositivo è un LUN ONTAP(R)". È causato dal fatto che FLI si affida alla tecnologia FlexArray che non supporta la virtualizzazione delle destinazioni ONTAP o ONTAP. FLI è in grado di importare le LUN, tuttavia FlexArray non supporta la virtualizzazione.

====
+
[listing]
----
cluster::*> storage errors show
Disk: NET-1.1
UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.1 (60a9800044306931452b47385767366b): This device is an ONTAP(R) LUN.

Disk: NET-1.2
UID: 60A98000:44306931:452B4738:5767366D:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.2 (60a9800044306931452b47385767366d): This device is an ONTAP(R) LUN.

2 entries were displayed.
----
. Visualizzare i dettagli del LUN di origine.
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981880b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-6
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981980b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-5
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

~~~~~~ Output truncated ~~~~~~~
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Verificare che l'array di origine venga rilevato attraverso tutte le porte dell'iniziatore.
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Elencare i LUN mappati dallo storage 7-Mode. Verificare le proprietà e i percorsi del disco.
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1 -instance
                  Disk: NET-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_LUN_1
                Vendor: NETAPP
                 Model: LUN
         Serial Number: D0i1E+G8Wg6k
                   UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0

Errors:
NET-1.1 (60a9800044306931452b47385767366b): This device is a ONTAP(R) LUN.
~~~~~~ Output truncated ~~~~~~~
2 entries were displayed.
----
. Verificare che il LUN di origine sia contrassegnato come estraneo.
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
NET-1.1                   -     -   - LUN     unassigned  -         -
NET-1.2                   -     -   - LUN     foreign     -         -
2 entries were displayed.
----
. I numeri di serie vengono utilizzati nei comandi di importazione LUN FLI. Elencare tutti i LUN esterni e i relativi numeri di serie.
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
NET-1.2 D0i1E+G8Wg6m
----
. Creare il LUN di destinazione. Il `LUN create` Il comando rileva le dimensioni e l'allineamento in base all'offset della partizione e crea il LUN di conseguenza con l'argomento del disco esterno
+
[listing]
----
cluster::*> vol create -vserver fli_72C -volume flivol -aggregate aggr1 -size 10G
[Job 12523] Job succeeded: Successful
----
. Verificare il volume.
+
[listing]
----
cluster::*> vol show -vserver fli_72C
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli_72C   flivol       aggr1        online     RW         10GB     9.50GB    5%
fli_72C   rootvol      aggr1        online     RW          1GB    972.6MB    5%
2 entries were displayed.
----
. Creare il LUN di destinazione.
+
[listing]
----
cluster::*> lun create -vserver fli_72C -path /vol/flivol/72Clun1 -ostype windows_2008 -foreign-disk D0i1E+G8Wg6m

Created a LUN of size 3g (3224309760)
----
. Verificare il nuovo LUN.
+
[listing]
----
cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             online  unmapped windows_2008
                                                                      3.00GB
----
. Creare un igroup del protocollo FCP con gli iniziatori host.
+
[listing]
----
cluster::*> lun igroup create -vserver fli_72C -igroup 72C_g1 -protocol fcp -ostype windows –initiator 10:00:00:00:c9:e6:e2:79

cluster::*> lun igroup show -vserver fli_72C -igroup 72C_g1
          Vserver Name: fli_72C
           Igroup Name: 72C_g1
              Protocol: fcp
               OS Type: windows
Portset Binding Igroup: -
           Igroup UUID: 7bc184b1-dcac-11e4-9a88-00a0981cc318
                  ALUA: true
            Initiators: 10:00:00:00:c9:e6:e2:79 (logged in)
----
. Mappare il LUN di prova sull'igroup di test.
+
[listing]
----
cluster::*> lun map -vserver fli_72C -path /vol/flivol/72Clun1 -igroup 72C_g1

cluster::*> lun mapping show -vserver fli_72C
Vserver    Path                                      Igroup   LUN ID  Protocol
---------- ----------------------------------------  -------  ------  --------
fli_72C    /vol/flivol/72Clun1                       72C_g1        0  fcp
----
. Offline il LUN di prova.
+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1

Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y

cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             offline mapped   windows_2008
                                                                      3.00GB
----
. Creare una relazione di importazione tra il nuovo LUN e il LUN esterno.
+
[listing]
----
cluster::*> lun import create -vserver fli_72C -path /vol/flivol/72Clun1 -foreign-disk D0i1E+G8Wg6m

cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 import    stopped
                                                           stopped            0
----

